language: python
sudo: false
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYPI_USER_NAME: chaostoolkit
    - secure: "Hrf7gE9x6f1RN7c6TwucOpyQWscf92G6fWo7x3f7ed4QguQ0Vyg2Z+vOq1tmVfpyFpheCdRUwqDCqRpS/0PRnDMJmpqB1h6N1sNeVjy9i8W1c6MPe9UxaNZadR9m90DjI/MT2RKBzO2pbvucUCYTp0ueX3tfI90DrJtR2fH487blje9YuS5RTxAeRvDoOwbZBwI8wx7gjGjhD2DgYvMGcZiAe7119xvKiCL4YnNtcoJRqHeC76u7FbKrm5Cpb97fzLPkIxSU0KtdaV/pTuCswuBIWEY4kQi2svNw3121ddT5GUlFVijnosifrmIBnxuef8XN9ADNSWxWVWMemM65qCdLKN0bknu4+ND0UjSTLfOEPHYyedqLPG7p8OfWSfRhPiXk4Iaf5ovP+Pxw2XqR6csSPSOoHAR1RXcILYMfOe1NS2SuoD57mWDy5pRR2b5xfQIl6OpARd2dwugeLb/WsN5Za2U5Lb96aziRQU/yQ2lTdfs1S1CN3aPxgTKgCL4gb1Wc2mnFMBeYLAiEskdbAZtnSkWWSUl628ydd8BY9nNuhGbcXc8OVWrXwaXEYhySAOyexm9XF6+F06i264UGlxBWJp6MQYbkZTfNfc4pNxoZGfQIDXJrVX84XE2lsvqk4oAMfBSKmoRgO55NouTKppT3Ghc2iMtkNS8F+4TbAMc="

python:
  - "3.6"
  - "3.7-dev"
install:
  - virtualenv --version
  - easy_install --version
  - pip --version
  - pip install --pre -r requirements.txt -r requirements-dev.txt
script:
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - "https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF"
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
